# Metodo de Thomas


In [8]:
import numpy as np
import matplotlib.pyplot as plt
from math import pi, fabs , sqrt
import random
from sympy import *

def Thomas(a,L,U):
    L[0][0] = a[0][0]
    L[1][0] = a[1][0]
    U[0][1] = a[0][1]/L[0][0]
    
    for k in range(0,len(a)):
        for i in range(2,len(a)-1):
            L[i][i] = a[i][i]-(a[i][i] *U[i-1][i])
            L[i+1][i] = a[i+1][i]
            U[i][i+1] = a[i][i+1]/L[i][i]
            
        L[k][k] = a[k][k-1]-(a[i][i] * U[k-1][k])
    
    print("L = ",L)
    print("U = ", U)

a = np.array([[2, -1, 0,0], [-1, 2, -1,0], [0,-1,2,-1],[0,0,-1,2]])  #matriz de 4x4
L=np.array([[0,0,0,0], [0,0,0,0], [0,0,0,0],[0,0,0,0]]) #matriz nula de 4x4
U=np.array([[1,0,0,0], [0,1,0,0], [0,0,1,0],[0,0,0,1]])  #matriz de 4x4


print("A = ", a)
Thomas(a,L,U)

A =  [[ 2 -1  0  0]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [ 0  0 -1  2]]
L =  [[ 0  0  0  0]
 [-1 -1  0  0]
 [ 0  0  2  0]
 [ 0  0 -1 -1]]
U =  [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
def TDMASolve(a, b, c, d):
    n = len(d)  # número de filas

    # Modifica los coeficientes de la primera fila
    c[0] /= b[0]  # Posible división por cero
    d[0] /= b[0]

    for i in range(1, n):
        ptemp = b[i] - (a[i] * c[i-1])
        c[i] /= ptemp
        d[i] = (d[i] - a[i] * d[i-1])/ptemp

    # Sustitución hacia atrás
    x = [0 for i in range(n)]
    x[-1] = d[-1]

    for i in range(-2, -n-1, -1):
        x[i] = d[i] - c[i] * x[i+1]

    return x